GCmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from contas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', include('contas.urls')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as vw
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', vw.LoginView.as_view(), name='login'),
    path('logout/', vw.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('password_change/', vw.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', vw.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

images/urls.py
from django.urls import path
from images import views

app_name = 'images'
urlpatterns = [
    path('create/', views.image_create, name='create'),
]

set/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%y/%m/%d/', blank=True)

    def __str__(self):
        return f'Profile for {self.user.username}'

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify


# Create your models here.
class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import Profile


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_birth', 'photo')


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput({'placeholder': 'Type your password'}))
    password2 = forms.CharField(label='Retype password', widget=forms.PasswordInput({'placeholder': 'Retype your password'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match.")
        return cd['password2']


class LoginForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput({'placeholder': 'Type your name'}))
    password = forms.CharField(widget=forms.PasswordInput({'placeholder': 'Type your password'}))

images/forms.py
from urllib import request

from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from images.models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']

        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match a valid image extensions.')
        return url

    def save(self, force_insert=False,
             force_update=False,
             commit=True):
        image = super().save(commit=False)

        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        # download image from the given URL
        response = request.urlopen(image_url)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

from accounts.forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from accounts.models import Profile


# Create your views here
def index(request):
    return render(request, 'index.html')


@login_required
def dashboard(request):
    return render(request, 'dashboard.html', {'user': request.user})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html',
                  {'user_form': user_form, 'profile_form': profile_form})


def inicio(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            usuario = authenticate(request, username=cd['name'], password=cd['password'])
            if usuario is not None:
                if usuario.is_active:
                    login(request, usuario)
                    return HttpResponse('Usuario autenticado!')
                else:
                    return HttpResponse('Conta desativada!')
            else:
                return HttpResponse('Inicio de sessao invalido!')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, 'registration/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html',
                  {'form': user_form})

images/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from images.forms import ImageCreateForm


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Image added successfully')
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
    return render(request, 'create.html', {'section': 'images', 'form': form})

accounts/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/js/bootstrap.js' %}"></script>
  <script src="{% static '/js/jquery-3.5.1.js' %}"></script>

  <!--link rel="apple-touch-icon" sizes="180x180"
        href="{% static '/img/favicon/apple-touch-icon.png' %}">
  <link rel="icon" sizes="32x32" href="{% static '/img/favicon/favicon-32x32.png' %}"
        type="image/png">
  <link rel="icon" sizes="16x16" href="{% static '/img/favicon/favicon-16x16.png' %}"
        type="image/png">
  <link rel="shortcut icon" href="{% static '/img/favicon/favicon.ico' %}" type="image/x-icon">
  <link rel="manifest" href="{% static '/img/favicon/site.webmanifest' %}"-->

  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>GCmarks</title>
  {% endif %}

  {% block extra_head %}{% endblock extra_head %}
</head>
<body class="bg-dark">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
  <a class="navbar-brand" href="{% url 'accounts:index' %}">GCmarks</a>

  <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="true"
      aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:dashboard' %}">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'images:create' %}">Images</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <span class="navbar-text"><b>Hello, {{ user.username }}</b> -</span>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <span class="navbar-text"><b>Hello, Dude</b> -</span>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
<main role="main" class="container bg-light" style="padding: 10px; border-radius: 5px;">
  <div class="pb-2 mb-2 border-bottom">
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li class="{{ message.tags }}">
        {{ message|safe }}
        <a href="#" class="close">X</a>
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    {% block page_header %}{% endblock page_header %}
  </div>
  <div>{% block content %}{% endblock content %}</div>
</main>
</body>
</html>

accounts/templates/dashboard.html
{% extends 'base.html' %}

{% block page_header %}
<h1>Dashboard</h1>
{% endblock page_header %}

{% block content %}
<p>
  Welcome to your dashboard {{ user.username }}.<br>
  You can <a href="{% url 'accounts:edit' %}">edit your profile</a>
  or <a href="{% url 'accounts:password_change' %}">change your password</a>.
</p>
{% endblock content %}

accounts/templates/index.html
{% extends 'base.html' %}

{% block page_header %}
<h1>Hello world</h1>
{% endblock page_header %}

{% block content %}
<p>Welcome Dude..</p>
{% endblock content %}

contas/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
  <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/js/bootstrap.js' %}"></script>
  <script src="{% static '/js/jquery-3.5.1.js' %}"></script>

  <!--link rel="apple-touch-icon" sizes="180x180"
        href="{% static '/img/favicon/apple-touch-icon.png' %}">
  <link rel="icon" sizes="32x32" href="{% static '/img/favicon/favicon-32x32.png' %}"
        type="image/png">
  <link rel="icon" sizes="16x16" href="{% static '/img/favicon/favicon-16x16.png' %}"
        type="image/png">
  <link rel="shortcut icon" href="{% static '/img/favicon/favicon.ico' %}" type="image/x-icon">
  <link rel="manifest" href="{% static '/img/favicon/site.webmanifest' %}"-->

  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>GCmarks</title>
  {% endif %}

  {% block extra_head %}{% endblock extra_head %}
</head>
<body class="bg-light">
<nav class="navbar navbar-expand-md navbar-light bg-dark mb-4 border">
  <a class="navbar-brand" href="{% url 'contas:inicio' %}">GCmarks</a>

  <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contas:inicio' %}" title=""></a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <span class="navbar-text"><b>Olaa, {{ user.username }}!</b> -</span>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'contas:logout' %}">Terminar sessao</a>
      </li>
      {% else %}
      <li class="nav-item">
        <span class="navbar-text"><b>Olaa, Companheiro!</b> -</span>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'contas:inicio' %}">Inicie sessao</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'contas:cadastrar' %}">Cadastre-se</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
<main role="main" class="container bg-dark" style="padding: 10px; border-radius: 5px;">
  <div class="pb-2 mb-2 border-bottom">
    {% block page_header %}{% endblock page_header %}
  </div>
  <div>{% block content %}{% endblock content %}</div>
</main>
</body>
</html>

images/templates/create.html
{% extends 'base.html' %}{% load bootstrap4 %}

{% block extra_head %}{% endblock extra_head %}

{% block page_header %}
<h1>Bookmark an image</h1>
{% endblock page_header %}

{% block content %}
<img src="{{ request.GET.url }}" class="image-preview">
<form method="post">
  {{ bootstrap_form form }}
  {% csrf_token %}
  {{ buttons }}
  <input type="submit" value="Bookmark it!">
  {{ endbuttons }}
</form>
{% endblock content %}